<?php

namespace App\Services;

use App\Services\Concerns\FichaCaracterizacionValidation\HandlesFichaCaracterizacionValidationAdicionalesHelpers;
use App\Services\Concerns\FichaCaracterizacionValidation\HandlesFichaCaracterizacionValidationCompletaActions;
use App\Services\Concerns\FichaCaracterizacionValidation\HandlesFichaCaracterizacionValidationEdicionActions;
use App\Services\Concerns\FichaCaracterizacionValidation\HandlesFichaCaracterizacionValidationEliminacionActions;
use App\Traits\ValidacionesSena;

class FichaCaracterizacionValidationService
{
    use HandlesFichaCaracterizacionValidationAdicionalesHelpers;
    use HandlesFichaCaracterizacionValidationCompletaActions;
    use HandlesFichaCaracterizacionValidationEdicionActions;
    use HandlesFichaCaracterizacionValidationEliminacionActions;
    use ValidacionesSena;
}
